/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grupo3a.tp_diseno.Vista.Bedel.RegistrarReserva;

/**
 *
 * @author imsac
 */
public class EsporadicaTablaColumna extends javax.swing.JPanel {

    /**
     * Creates new form EsporadicaTablaColumna
     */
    public EsporadicaTablaColumna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMartesHorario = new javax.swing.JComboBox<>();
        cbMartesHorario1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        cbMartesHorario.setBackground(new java.awt.Color(40, 40, 40));
        cbMartesHorario.setForeground(new java.awt.Color(255, 255, 255));
        cbMartesHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ingrese..." }));
        cbMartesHorario.setDoubleBuffered(true);
        cbMartesHorario.setEnabled(false);
        cbMartesHorario.setFocusable(false);
        cbMartesHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMartesHorarioActionPerformed(evt);
            }
        });
        add(cbMartesHorario);

        cbMartesHorario1.setBackground(new java.awt.Color(40, 40, 40));
        cbMartesHorario1.setForeground(new java.awt.Color(255, 255, 255));
        cbMartesHorario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ingrese..." }));
        cbMartesHorario1.setDoubleBuffered(true);
        cbMartesHorario1.setEnabled(false);
        cbMartesHorario1.setFocusable(false);
        cbMartesHorario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMartesHorario1ActionPerformed(evt);
            }
        });
        add(cbMartesHorario1);

        jButton1.setLabel("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void cbMartesHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMartesHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMartesHorarioActionPerformed

    private void cbMartesHorario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMartesHorario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMartesHorario1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMartesHorario;
    private javax.swing.JComboBox<String> cbMartesHorario1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
